function m(b,a,c,d){b.m.kb(b.pb,a,c,d)}function n(b,a,c,d){b.m.ba?m(b,a,c,d):b.m.Oe()._OnMessageFromDOM({type:"event",component:b.pb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.m.B(b.pb,a,c)}function aa(b,a){for(const [c,d]of a)q(b,c,d)}function v(b){b.Ub||(b.m.yc(b.de),b.Ub=!0)}window.Hb=class{constructor(b,a){this.m=b;this.pb=a;this.Ub=!1;this.de=()=>this.Na()}jd(){}Na(){}};
window.Bf=class{constructor(){this.ed=-1}j(){-1!==this.ed&&(self.clearTimeout(this.ed),this.ed=-1)}};"use strict";function ba(b,a){q(b,"get-element",c=>{const d=w(b,c.elementId);return a(d,c)})}function w(b,a){b=b.Sa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Sb}
window.nd=class extends self.Hb{constructor(b,a){super(b,a);this.Sa=new Map;this.nb=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=w(this,c);this.nb&&d.parentElement.removeChild(d);this.Sa.delete(c)}],["set-visible",c=>{if(this.nb){var d=this.Sa.get(c.elementId),e=d.Sb;d.Nd?e.style.display=c.isVisible?"":"none":d.gf=!!c.isVisible}}],["update-position",c=>{if(this.nb){var d=this.Sa.get(c.elementId),e=d.Sb,f=this.m;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.mf=g;g=f.pd(g);g!==d.Ea&&(e.remove(),f.Ib(g).appendChild(e),d.Ea=g,f.Hc());c=c.htmlZIndex;c!==d.Pc&&(d.Pc=c,f.Hc());d.Nd||(d.Nd=!0,d.gf&&(e.style.display=""))}}],["update-state",c=>{w(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=w(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=w(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{w(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{w(this,c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.rf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.vf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function fa(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let z=new Audio;
const ha={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ia(b){b=await ja(b);return(new TextDecoder("utf-8")).decode(b)}
function ja(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const A=[];let C=0;window.RealFile=window.File;const D=[],F=new Map,G=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.Lb=class b{constructor(a){this.ba=a.xf;this.wa=null;this.aa="";this.$a=a.uf;this.Fb={};this.Ua=this.ta=null;this.Ra=[];this.ma=null;this.Rd=!0;this.M=[];this.Zc=[];this.$c=!1;this.ee=()=>this.Me();this.Rc=!1;this.Kd=0;this.ub=null;this.Za=-1;this.lf=()=>this.Xe();this.Cb=new Set;this.fd=null;this.fe=[];this.A=a.ge;this.Vb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ba=!1;da&&(this.ba=!1);if("cordova"===this.A&&this.ba&&x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.La()?self.chrome.webview.addEventListener("message",c=>this.zd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.zd(c));this.Yb=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.af(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Se());this.B("runtime","cordova-fetch-local-file",c=>this.Te(c));this.B("runtime","create-job-worker",()=>this.Ue());this.B("runtime","send-wrapper-extension-message",c=>this.$e(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.xd(a)):this.xd(a)}j(){this.zc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ua&&(this.Ua.j(),this.Ua=null);for(const {canvas:a,
cb:c}of this.M)a.remove(),c.remove();this.M.length=0}ye(){return this.M[0].canvas}pd(a){return Math.min(a,this.M.length-1)}Ib(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].cb}_GetHTMLWrapElement(a){return this.Ib(a)}Ce(){return ca&&"cordova"===this.A}ib(){const a=navigator.userAgent;return ca&&pa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ae(){return x}qd(){return x&&pa.has(this.A)}sd(){return"windows-webview2"===this.A||!!("preview"===
this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}La(){return this.sd()||"xbox-uwp-webview2"===this.A}async xd(a){this.ba&&!await fa()&&(this.ba=!1);"macos-wkwebview"===this.A?this.lb({type:"ready"}):this.La()&&(this.cf(),this.fe=(await this.Re()).registeredComponentIds);if("playable-ad"===this.A){this.qa=self.c3_base64files;this.Yb={};await this.Je();for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Yb.hasOwnProperty(c)?a.bb[d]={rf:!0,vf:this.Yb[c]}:this.qa.hasOwnProperty(c)&&
(a.bb[d]=URL.createObjectURL(this.qa[c]))}a.mc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.yc(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.tf?this.aa=a.tf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.zf&&(this.Fb=a.zf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.We(d));this.ub=new self.De(this);await ra(this.ub);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Qe(a,c.port2):await this.Pe(a,c.port2)}Bc(a){a=this.Fb.hasOwnProperty(a)?this.Fb[a]:a.endsWith("/workermain.js")&&this.Fb.hasOwnProperty("workermain.js")?
this.Fb["workermain.js"]:"playable-ad"===this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Vb)return a=await this.Gb(d.qf?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}rc(){return this.La()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}wd(a){var c=this.aa,d=location.href,e=this.oa(),
f=this.ga(),g=this.rc(),h=window.devicePixelRatio,k=b.hb(),l=a.Ef,p=window.cr_previewImageBlobs||this.qa,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.ge;var Y=(new URLSearchParams(self.location.search)).has("debug"),E=this.ub;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,
exportType:a,isDebug:Y,ife:!!self.Df,jobScheduler:{inputPort:E.Qc,outputPort:E.Yc,maxNumWorkers:E.hf},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$a+"opus.wasm.wasm",isFileProtocol:this.Vb,isiOSCordova:this.Ce(),isiOSWebView:this.ib(),isWindowsWebView2:this.sd(),isAnyWebView2Wrapper:this.La(),wrapperComponentIds:this.fe,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Qe(a,c){const d=
this.Bc(a.yf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ta.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ta.addEventListener("message",r);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ta=await this.pc(d,this.aa,{type:"module",name:"Runtime",qf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();
document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,cb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.mc||[],k=a.bb;h=await Promise.all(h.map(l=>this.Oa(l)));k=await Promise.all(k.map(l=>this.Oa(l)));if("cordova"===this.A)for(let l=0,p=a.lc.length;l<p;++l){const r=a.lc[l],t=r[0];if(t===a.gd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Oa(t)}this.ta.postMessage(Object.assign(this.wd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.lc,mainProjectScript:a.gd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...sa(this.ub)]);this.Ra=D.map(l=>new l(this));this.vd();H(e);ta(g);ua(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.td(r.pb,"js-invoke-function",{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.kb("runtime","go-to-last-error-script"))}async Pe(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,cb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ra=D.map(h=>new h(this));this.vd();H(d);ta(e);e=a.bb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.mc)){var f=[...a.mc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Oa(h)));await Promise.all(e.map(h=>y(h)));e=self.C3_ProjectScriptsStatus;f=a.gd;const g=a.lc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Oa(k),await y(k),"preview"!==this.A||e[h]||this.Bd(h,"main script did not run to completion")}catch(l){this.Bd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Oa(k),await y(k);"preview"===this.A&&"object"!==typeof self.Af.Cf?(this.Ob(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.wd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:oa}),ua(this.ma),this.yd(),this.Ua=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ua,a))}Bd(a,c){this.Ob();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Ob()}Ob(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ue(){const a=await va(this.ub);return{outputPort:a,transferables:[a]}}af(a){if(!this.Rc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,cb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Rd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Rd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,cb:p}=this.M.pop();p.remove();this.ba&&!d?this.Zc.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,H(c),ta(d),this.M.push({canvas:c,cb:d});for(const l of this.Ra)if(l instanceof window.nd&&l.nb)for(const p of l.Sa.values())e=l.m.pd(p.mf),f=p.Ea,-1!==
e&&-1!==f&&e!==f&&(f=p.Sb,f.remove(),l.m.Ib(e).appendChild(f),p.Ea=e);this.Hc();return{addedCanvases:a,transferables:k}}Se(){for(const a of this.Zc)a.remove();this.Zc.length=0}Hc(){this.$c||(this.$c=!0,this.yc(this.ee))}Me(){this.Ad(this.ee);this.$c=!1;let a=[];for(var c of this.Ra)if(c instanceof window.nd){var d=c.nb?[...c.Sa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ea,l=h.Ea;return k!==l?k-l:g.Pc-h.Pc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ea!==c&&(this.ud(c,a.slice(d,
e)),c=g.Ea,d=e)}d<e&&this.ud(c,a.slice(d,e))}ud(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Sb);var d=new Set(c);a=this.Ib(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Oe(){if(this.ba)throw Error("not available in worker mode");return this.Ua}kb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}td(a,c,d,e,f){const g=na++,h=new Promise((k,l)=>{G.set(g,{resolve:k,reject:l})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ve(a);if("result"===c)this.Ye(a);else if("runtime-ready"===c)this.Ze();else if("alert-error"===c)this.Ob(),alert(a.message);else if("creating-runtime"===c)this.yd();else throw Error(`unknown message '${c}'`);}Ve(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Nb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Nb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Nb(f,!1,""+h)}):this.Nb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Nb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ye(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}B(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static nc(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}vd(){for(const a of this.Ra)if("runtime"===a.pb){this.ma=a;return}throw Error("cannot find runtime DOM handler");
}We(a){this.kb("debugger","message",a)}Ze(){for(const a of this.Ra)a.jd()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||qa)}static Cd(a){qa=!!a}yc(a){this.Cb.add(a);this.Gc()}Ad(a){this.Cb.delete(a);0===this.Cb.size&&this.zc()}Gc(){-1===this.Za&&0<this.Cb.size&&(this.Za=requestAnimationFrame(this.lf))}zc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Xe(){this.Za=-1;for(const a of this.Cb)a();this.Gc()}Ca(a){this.ma.Ca(a)}Ma(a){this.ma.Ma(a)}Fc(){this.ma.Fc()}Mb(a){this.ma.Mb(a)}Be(){return!!ha["audio/webm; codecs=opus"]}async df(a){a=
await this.td("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Fe(a){this.Rc=!0;this.Kd=a}ze(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}rd(a){return!this.ze(a)}async Oa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Vb&&this.rd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Gb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Te(a){const c=a.filename;switch(a.as){case "text":return await this.xe(c);
case "buffer":return await this.Gb(c);default:throw Error("unsupported type");}}md(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async xe(a){a=await this.md(a);return await ia(a)}Ac(){if(A.length&&!(8<=C)){C++;var a=A.shift();this.Ke(a.filename,a.wf,a.pf)}}Gb(a){return new Promise((c,d)=>{A.push({filename:a,wf:e=>{C--;this.Ac();c(e)},pf:e=>{C--;this.Ac();d(e)}});this.Ac()})}async Ke(a,c,d){try{const e=
await this.md(a),f=await ja(e);c(f)}catch(e){d(e)}}zd(a){if("entered-fullscreen"===a)b.Cd(!0),I(this.ma);else if("exited-fullscreen"===a)b.Cd(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"directory-handles"!==c&&("wrapper-init-response"===c?(this.fd(a),this.fd=null):"extension-message"===c?this.kb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}$e(a){this.lb({type:"extension-message",componentId:a.componentId,
messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}lb(a){this.La()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}cf(){window.moveTo=(a,c)=>{this.lb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.lb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Re(){return this.La()?new Promise(a=>{this.fd=a;this.lb({type:"wrapper-init"})}):
Promise.resolve()}async Je(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.Ie(c,d));await Promise.all(a)}async Ie(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=await this.Ne(c);d||(d=this.Le(c));this.qa[a]=d}}async Ne(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Le(a){a=this.bf(a);return this.He(a.data,a.sf)}bf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{sf:a,data:d}}He(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.Lb,wa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},xa={dispatchUserScriptEvent:!0},ya={dispatchRuntimeEvent:!0};function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Aa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ba(b){b=URL.createObjectURL(b);try{return await Aa(b)}finally{URL.revokeObjectURL(b)}}function Ca(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);
function L(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ba(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ha=!1;document.addEventListener("pause",()=>Ha=!0);document.addEventListener("resume",()=>Ha=!1);function H(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function ta(b){b.addEventListener("selectstart",Fa);b.addEventListener("gesturehold",Fa);b.addEventListener("touchstart",Fa)}function ua(b){b.Jd=!0;b.Uc=b.m.oa();b.vb=b.m.ga()}
function I(b){if(!b.ka){var a=J.hb();a&&"any"!==b.cd&&Ia(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.Id=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,"hidden"===document.visibilityState));b.bc=!("hidden"!==document.visibilityState&&!Ha);return{isSuspended:b.bc}}
function Pa(b){b.Ed||(b.Ed=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Qa(b){b.Dd||(b.Dd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ra(b){await za(b.url)}
function Sa(b,a){b.Ld=a.message;-1===b.Lc&&(b.Lc=setTimeout(()=>{b.Lc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ld)},250))}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.hb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Oa(b,a){b.bc!==a&&((b.bc=a)?b.m.zc():b.m.Gc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.ib()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Ua(b,a,c){"Backspace"===c.key&&L(c);"nwjs"===b.m.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ka){var d=wa.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function M(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.Wc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.Wc=c.buttons)}}function Va(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.za=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.za=a))}}
function Wa(b,a,c,d){const e=b.oa(),f=b.ga();b.ab=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb(),cssDisplayMode:b.m.rc()}):10>d&&Xa(b,e,f,d+1)}function Xa(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>Wa(b,a,c,d),48)}
function Ia(b){b=b.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.nc(class extends self.Hb{constructor(b){super(b,"runtime");this.Jd=!1;this.ab=-1;this.cd="any";this.bc=this.Dd=this.Ed=!1;this.ic=document.createElement("div");this.ic.className="c3-screen-reader-text";this.ic.setAttribute("aria-live","polite");document.body.appendChild(this.ic);this.Ga=null;this.ka=!1;this.Ld="";this.Lc=-1;this.Id=!1;this.Uc=b.oa();this.vb=b.ga();this.za=this.Eb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ja(c));b.B("runtime","raster-svg-image",c=>Ka(c));b.B("runtime","get-svg-image-size",c=>La(c));b.B("runtime","set-target-orientation",c=>{this.cd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ma(c));b.B("runtime","go-to-script",c=>Ma(c));b.B("runtime","before-start-ticking",()=>Na(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Pa(this));b.B("runtime","enable-device-motion",()=>Qa(this));b.B("runtime","add-stylesheet",c=>Ra(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.ic.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.ye().style.display="";this.m.Fe(c.duration)});b.B("runtime","export-to-video-progress",c=>Sa(this,c));b.B("runtime","exported-to-video",c=>{window.nf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.nf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ca(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.Wc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Jd){var c=this.oa();var d=this.ga();if(this.m.qd()){if(this.Id){if(this.Uc===
c&&d<this.vb){this.Eb=this.vb-d;Va(this,this.vb,this.Eb);c=void 0;break a}0<this.Eb&&(this.Eb=0,Va(this,d,this.Eb))}this.Uc=c;this.vb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb(),cssDisplayMode:this.m.rc()});this.m.ib()&&(-1!==this.ab&&clearTimeout(this.ab),Wa(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",c=>Ta(this,c));window.addEventListener("webkitfullscreenerror",c=>Ta(this,c));window.addEventListener("mozfullscreenerror",c=>Ta(this,c));if(b.ib()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Va=new Set;this.$b=new WeakSet;this.va=!1}jd(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,ya)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},ya);this.Wc=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||Ca(a))&&m(this,"keyboard-blur",null,ya)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,
xa));window.addEventListener("mousemove",a=>M(this,"mousemove",a,xa));window.addEventListener("mouseup",a=>M(this,"mouseup",a,xa));window.addEventListener("dblclick",a=>M(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.za,pageX:a.pageX,pageY:a.pageY+this.za,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
Ya(a.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.m.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Fc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.m.Ae()&&!this.m.qd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.ib()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.m.oa()}ga(){return this.m.ga()}Fc(){var b=
[...this.Va];this.Va.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Va.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Va.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Va.add(b)})}Ma(b){this.Va.delete(b);this.$b.add(b)}Mb(b){this.va=!!b}});"use strict";
async function ra(b){if(b.ef)throw Error("already initialised");b.ef=!0;var a=b.xa.Bc(("playable-ad"===b.xa.A?b.xa.$a:"")+"dispatchworker.js");b.Kc=await b.xa.pc(a,b.ob,{name:"DispatchWorker"});a=new MessageChannel;b.Qc=a.port1;b.Kc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await va(b)}function sa(b){return[b.Qc,b.Yc]}
async function va(b){const a=b.Sd.length;var c=b.xa.Bc(("playable-ad"===b.xa.A?b.xa.$a:"")+"jobworker.js");c=await b.xa.pc(c,b.ob,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Kc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Sd.push(c);return e.port1}
self.De=class{constructor(b){this.xa=b;this.ob=b.aa;this.ob="preview"===b.A?this.ob+"workers/":this.ob+b.$a;this.hf=Math.min(navigator.hardwareConcurrency||2,16);this.Kc=null;this.Sd=[];this.Yc=this.Qc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Lb({xf:!0,yf:"workermain.js",bb:["scripts/c3runtime.js"],lc:[],gd:"",uf:"scripts/",mc:[],ge:"html5"}));"use strict";
async function Za(b,a){a=a.type;let c=!0;0===a?c=await $a():1===a&&(c=await ab());m(b,"permission-result",{type:a,result:c})}async function $a(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function ab(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Lb.nc(class extends self.Hb{constructor(b){super(b,"touch");q(this,"request-permission",a=>Za(this,a))}});"use strict";const bb=180/Math.PI;
async function cb(b,a){a.usePlayMusicAsSoundWorkaround&&(b.dc=!0);b.dd=a.timeScaleMode;b.Xd=["equalpower","HRTF","soundfield"][a.panningModel];b.Hd=["linear","inverse","exponential"][a.distanceModel];b.Yd=a.refDistance;b.Wd=a.maxDistance;b.$d=a.rolloffFactor;if(b.m.Rc)b.dc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Kd)});else{var c={latencyHint:a.latencyHint};b.ce||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");db(b);b.g.onstatechange=()=>{"running"!==b.g.state&&db(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function fb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Td=g.slice(0);gb(b,g);try{b.R=await hb(b,c,d,e,g,f);if(p){P(b.R,!0);var u=b.R,Y=p.x,E=p.y,vb=p.z,wb=p.angle,ka=p.innerAngle,la=p.outerAngle,ma=p.outerGain;if(u.tb){ib(u,Y,E,vb,wb);var B=self.eb.Ge;
u.ra[0]!==B(ka)&&(u.ra[0]=B(ka),u.F.coneInnerAngle=B(ka));u.ra[1]!==B(la)&&(u.ra[1]=B(la),u.F.coneOuterAngle=B(la));u.ra[2]!==ma&&(u.ra[2]=ma,u.F.coneOuterGain=ma)}p.hasOwnProperty("uid")&&(b.R.pa=p.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),jb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(xb){console.error("[Construct] Audio: error starting playback: ",xb);return}finally{c=g.join(" ");d=b.Bb.get(c);if(!d)throw Error("expected pending tag");d.hd--;0===d.hd&&(d.resolve(),b.Bb.delete(c))}v(b)}
async function kb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await lb(b,c);for(const h of R(b,c))if(!h.ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ja=d;h.Ta=g;h.be=a}S(b)}async function mb(b,a){const c=a.tags;a=a.rate;await lb(b,c);for(const d of R(b,c))d.la!==a&&(d.la=a,d.Da())}async function nb(b,a){const c=a.tags;a=a.pos;await lb(b,c);for(const d of R(b,c))d.vc(a)}
async function ob(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await hb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function pb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function qb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.me(b,...e);else if("delay"===c)d=new self.ke(b,...e);else if("convolution"===c){var g=d=new self.je(b,f.ha,...e),h=a.bufferType;g.Fd=a.bufferOriginalUrl;g.Gd=h}else if("flanger"===c)d=
new self.ne(b,...e);else if("phaser"===c)d=new self.pe(b,...e);else if("gain"===c)d=new self.oe(b,...e);else if("stereopan"===c)d=new self.re(b,...e);else if("tremolo"===c)d=new self.se(b,...e);else if("ringmod"===c)d=new self.qe(b,...e);else if("distortion"===c)d=new self.le(b,...e);else if("compressor"===c)d=new self.ie(b,...e);else if("analyser"===c)d=new self.he(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Qd=l.length;d.bd=
h;l.push(d);rb(g,h)}sb(b)}
async function tb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.jc=a.timeScale;b.Mc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.va=a.isSilent;b.m.Mb(b.va);b.Zb=a.masterVolume;b.Qa.gain.value=
b.Zb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>qb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>ub(b,f,c)));S(b)}
async function yb(b,a){try{const c=b.g.suspend(a.time);b.Pd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.kb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>zb(d)),b.Pd=!0);await c}catch(c){zb(c)}}
function db(b){b.Tb||(b.Oc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Tb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ia)if(g.gb()===c)return await Ab(g),g;if(f)return null;if(e&&(b.dc||b.Od)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Aa()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.ce;e&&f&&(b.Od=!0);c=!e||b.dc||f?new self.ve(b,a,c,d,e,f):new self.te(b,a,c,d,e);b.ia.push(c);await Ab(c);b.Vd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Vd.add(a));return c}
function Bb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Cb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function rb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Db(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.Ha&&b.Vc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*Db(b,a){if(a)for(const c of b.H)Bb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Eb(b,a,c){return c?b.m.df(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Fb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Bb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function hb(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.oc()||f))return g.na=e,g;a=await O(b,a,c,d,f);e="html5"===a.Ic?new self.ue(a.u,a,e):new self.we(a.u,a,e);b.H.push(e);return e}
function gb(b,a){a=a.join(" ");let c=b.Bb.get(a);if(!c){let d=null;c={hd:0,promise:new Promise(e=>d=e),resolve:d};b.Bb.set(a,c)}c.hd++}function lb(b,a){return(b=b.Bb.get((0===a.length?b.Td:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Pa.size)v(b);else for(const a of b.H)if(!a.I&&!a.O()){v(b);break}}function Gb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function sb(b){b.Sc||(b.Sc=!0,Promise.resolve().then(()=>Ib(b)))}
function Ib(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.fb());m(b,"fxstate",{fxstate:a});b.Sc=!1}
async function ub(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await hb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],f=d.orient,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],e.setPosition(...b.Xa),e.setOrientation(...b.Wa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),jb(b,d));c.Play(k,l,p,0);a.isPlaying||c.jb();c.Dc(a)}}}function zb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.Hb{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Tb=this.Oc=!1;this.ya=()=>{if(!this.Oc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Tb&&(this.Oc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Tb=!1)}};this.ia=[];this.H=[];this.R=null;this.Td=[];this.Vd=new Set;this.Ud=-1;this.Bb=new Map;this.Zb=1;this.va=!1;this.dd=0;this.jc=1;this.Mc=0;this.Xd="HRTF";this.Hd="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Od=this.dc=!1;this.ce=this.m.Be();this.ja=new Map;this.Pa=new Set;this.Pd=this.Sc=!1;this.Vc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Vc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);
this.Ha.connect(Cb(this,this.Vc))};this.Rb=null;self.C3Audio_GetOutputStream=()=>{this.Rb||(this.Rb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Rb));return this.Rb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>cb(this,a)],["play",a=>fb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.jb():d.Kb();S(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>kb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Qa.gain.value=this.Zb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Jb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.m.Mb(this.va);for(const c of this.H)c.Pb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.wc(a)}],["set-playback-rate",a=>mb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),jb(d,a)}],["seek",a=>nb(this,a)],["preload",a=>ob(this,a)],["unload",a=>pb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.xc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>qb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);sb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);rb(this,a)}}],["tick",a=>{this.jc=a.timeScale;this.Mc=a.gameTime;this.Ud=a.tickCount;if(0!==this.dd)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&ib(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>tb(this,a)],["offline-render-audio",a=>yb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Qa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Jb(){return this.va}Ca(b){this.m.Ca(b)}Ma(b){this.m.Ma(b)}Na(){for(var b of this.Pa)b.Na();
b=this.g.currentTime;for(var a of this.H)a.Na(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.fb());m(this,"state",{tickCount:this.Ud,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.bd,index:c.Qd,peak:c.Ya,rms:c.Zd,binCount:c.l.frequencyBinCount,freqBins:c.Md}))});0===a.length&&0===this.Pa.size&&this.Ub&&(this.m.Ad(this.de),this.Ub=!1)}static Ge(b){return b*bb}static od(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Ee(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Lb.nc(self.eb);"use strict";function Ab(b){b.Xb||(b.Xb=b.Cc());return b.Xb}self.kd=class{constructor(b,a,c,d,e){this.u=b;this.kf=a;this.Ia=c;this.T=d;this.ff=e;this.Ic="";this.Xb=null}j(){this.Xb=this.u=null}Cc(){}V(){return this.u.V()}sc(){return this.kf}gb(){return this.Ia}qc(){return this.T}Aa(){return this.ff}fa(){}};"use strict";
self.te=class extends self.kd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ic="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.wb=this.xb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Ab=this.V().createGain();this.zb=null;this.L.addEventListener("canplay",()=>{this.xb&&(this.xb(),this.wb=this.xb=null);!this.zb&&this.L&&(this.zb=this.V().createMediaElementSource(this.L),this.zb.connect(this.Ab))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ia}' error: `,f);this.wb&&(this.wb(f),this.wb=this.xb=null)})}j(){Fb(this.u,this);this.Ab.disconnect();this.Ab=null;this.zb.disconnect();this.zb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Cc(){return new Promise((b,a)=>{this.xb=b;this.wb=a;this.L.src=this.Ia})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Kb(b){if(b.Fa)return b.Fa;var a=b.u.m;if("cordova"===a.A&&a.rd(b.Ia)&&a.Vb)b.Fa=await a.Gb(b.Ia);else{a=await fetch(b.Ia);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Mb(b){if(b.ha)return b.ha;b.ha=await Eb(b.u,b.Fa,b.jf);b.Fa=null}
self.ve=class extends self.kd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ic="webaudio";this.ha=this.Fa=null;this.jf=!!f}j(){Fb(this.u,this);this.ha=this.Fa=null;super.j()}async Cc(){try{await Kb(this),await Mb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ia}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Nb=0;
function P(b,a){a=!!a;b.tb!==a&&(b.tb=a,b.tb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Xd,b.F.distanceModel=b.u.Hd,b.F.refDistance=b.u.Yd,b.F.maxDistance=b.u.Wd,b.F.rolloffFactor=b.u.$d),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function Q(b,a){a=!!a;b.Wb!==a&&(b.Wb=a,b.Wb?(P(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function jb(b,a){b.Wb&&b.ad!==a&&(b.da.pan.value=a,b.ad=a)}function T(b,a){b.Ja=a;b.G.gain.cancelScheduledValues(0);b.Ta=-1;b.G.gain.value=b.tc()}function Jb(b,a){a=!!a;b.ua!==a&&(b.ua=a,b.Pb())}
function ib(b,a,c,d,e){if(b.tb){var f=b.Xa,g=b.Wa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Tc?b.u.Mc:performance.now()/1E3}
self.ld=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Qb=Nb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.tb=!1;this.Xa=[0,0,0];this.Wa=[0,0,0];this.ra=[0,0,0];this.da=null;this.Wb=!1;this.ad=0;this.I=!0;this.Y=this.sa=this.J=!1;this.Ja=1;this.ua=!1;this.la=1;b=this.u.dd;this.Tc=1===b&&!this.Aa()||2===b;this.Ta=this.pa=-1;this.be=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Cb(this.u,0<this.na.length?this.na[0]:"")}sc(){return this.P.sc()}gb(){return this.P.gb()}qc(){return this.P.qc()}Aa(){return this.P.Aa()}O(){}oc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ka(){}fa(){return this.P.fa()}Play(){}Ba(){}jb(){}Kb(){}Na(b){-1!==this.Ta&&b>=this.Ta&&(this.Ta=-1,this.be&&this.Ba(),Gb(this.u,"fade-ended",this.na,this.Qb))}tc(){const b=this.Ja;return isFinite(b)?b:0}Jb(){return this.u.Jb()}Pb(){}wc(){}Da(){}vc(){}xc(){}uc(){}fb(){var b=
this.Qb,a=this.na,c=this.fa(),d=-1===this.Ta?this.Ja:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Xa,orient:this.Wa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ka(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.sc(),bufferUrl:"",bufferType:this.qc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.ua,resumePosition:this.uc(),pan:f,stereoPan:this.da?
this.ad:null}}Dc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Jb(this,b.isMuted)}};"use strict";
self.ue=class extends self.ld{constructor(b,a,c){super(b,a,c);this.P.Ab.connect(this.G);this.P.onended=()=>this.Ec()}j(){this.Ba();this.P.Ab.disconnect();super.j()}W(){return this.P.W()}Ec(){this.I=!0;this.pa=-1;Gb(this.u,"ended",this.na,this.Qb)}O(){return this.W().ended}oc(){return this.I?!0:this.O()}Ka(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.ua=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.u.Ca(d);this.J=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.W();b.paused||b.pause();this.u.Ma(b);this.I=!0;this.J=!1;this.pa=-1}jb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Ma(b);this.J=!0}}Kb(){!this.J||this.I||this.O()||(this.u.Ca(this.W()),this.J=!1)}Pb(){this.W().muted=this.ua||this.Jb()}wc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Da(){let b=this.la;this.Tc&&(b*=this.u.jc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}vc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}uc(){return this.Ka()}xc(b){b?this.IsPlaying()?(this.W().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Ca(this.W()),this.sa=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.mb=null}
self.we=class extends self.ld{constructor(b,a,c){super(b,a,c);this.s=null;this.ac=d=>this.Ec(d);this.Nc=!0;this.mb=null;this.S=this.cc=this.ec=0;this.Xc=1}j(){this.Ba();V(this);this.ac=null;super.j()}Ec(b){this.J||this.sa||b.target!==this.mb||(this.I=this.Nc=!0,this.pa=-1,V(this),Gb(this.u,"ended",this.na,this.Qb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Nc}oc(){return!this.s||this.I?!0:this.O()}Ka(){let b;b=this.J?this.S:this.cc+(U(this)-this.ec)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.ua=!1;this.Xc=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.mb=this.s;this.s.onended=this.ac;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Nc=!1;this.Y=b;this.la=1;this.ec=U(this);this.cc=c}Ba(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.pa=-1}jb(){this.J||this.I||this.O()||(this.S=this.Ka(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Kb(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.mb=this.s,this.s.onended=this.ac,this.s.loop=this.Y,T(this,this.Ja),this.Da(),this.s.start(0,this.S),this.ec=U(this),this.cc=this.S,this.J=!1)}tc(){return super.tc()*this.Xc}Pb(){this.Xc=this.ua||this.Jb()?0:1;T(this,this.Ja)}wc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Da(){let b=this.la;this.Tc&&(b*=this.u.jc);this.s&&(this.s.playbackRate.value=b)}vc(b){this.I||this.O()||(this.J?this.S=b:(this.jb(),
this.S=b,this.Kb()))}uc(){return this.S}xc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.Ka(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.sa=!1:this.sa&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.mb=this.s,this.s.onended=this.ac,this.s.loop=this.Y,T(this,this.Ja),this.Da(),this.s.start(0,this.S),this.ec=U(this),this.cc=this.S,this.sa=!1)}Dc(b){super.Dc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Qd=-1;this.T=this.bd="";this.o=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.bd,params:this.o}}}
self.me=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.ke=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.yb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.rb=W(this);this.rb.gain.value=c;this.v.connect(this.yb);this.v.connect(this.h);this.yb.connect(this.i);this.yb.connect(this.X);this.X.connect(this.rb);this.rb.connect(this.yb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.yb.disconnect();
this.X.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.eb.od;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.rb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Gd=this.Fd="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.qb=this.g.createConvolver();this.qb.normalize=c;this.qb.buffer=a;this.v.connect(this.qb);this.v.connect(this.h);this.qb.connect(this.i)}j(){this.v.disconnect();this.qb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.Fd;b.bufferUrl="";b.bufferType=this.Gd;return b}};
self.ne=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.sb=W(this);this.sb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.sb);this.sb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.sb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.sb.gain,a/100,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.oe=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.od;switch(b){case 4:this.o[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.re=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.l.pan,a,c,d)}}};
self.se=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Db=W(this);this.Db.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Db.gain);this.C.start(0);this.v.connect(this.Db);this.v.connect(this.h);this.Db.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Db.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=W(this);this.hc=W(this);this.fc=W(this);b=d;.01>b&&(b=.01);this.hc.gain.value=b;this.fc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.kc=this.g.createWaveShaper();this.Jc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Jc[32768+e]=f,this.Jc[32768-
e-1]=-f;this.kc.curve=this.Jc;this.v.connect(this.hc);this.v.connect(this.h);this.hc.connect(this.kc);this.kc.connect(this.fc);this.fc.connect(this.i)}j(){this.v.disconnect();this.hc.disconnect();this.kc.disconnect();this.fc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.ie=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.he=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Md=new Float32Array(this.l.frequencyBinCount);this.ae=new Uint8Array(a);this.Zd=this.Ya=0;b=this.u;b.Pa.add(this);S(b)}j(){this.u.Pa.delete(this);this.l.disconnect();super.j()}Na(){this.l.getFloatFrequencyData(this.Md);this.l.getByteTimeDomainData(this.ae);const b=this.l.fftSize;let a=this.Ya=0;for(var c=0;c<b;++c){let d=(this.ae[c]-
128)/128;0>d&&(d=-d);this.Ya<d&&(this.Ya=d);a+=d*d}c=self.eb.Ee;this.Ya=c(this.Ya);this.Zd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
