function m(c,a,b,d){c.h.fa(c.W,a,b,d)}function r(c,a,b,d){c.h.m?m(c,a,b,d):c.h.Jb()._OnMessageFromDOM({type:"event",component:c.W,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.h.i(c.W,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.sa=class{constructor(c,a){this.h=c;this.W=a}Ta(){}};window.sc=class{constructor(){}};"use strict";class aa{constructor(c){this.X=c;this.Ea=!1;this.Ha=!0;this.Y=this.v=this.Qa=-1}}
function ba(c,a){const b=a.elementId,d=c.Va(b,a),e=new aa(d);c.F.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.Ha=!!a.isVisible;var f=c.xa(d);f.addEventListener("focus",()=>{v(c,"elem-focused",b)});f.addEventListener("blur",()=>{v(c,"elem-blurred",b)});f=a.htmlIndex;e.Qa=f;e.Y=a.htmlZIndex;c.J&&(a=c.h.ta(f),e.v=a,c.h.R(a).appendChild(d))}function ca(c,a){t(c,"get-element",b=>{const d=w(c,b.elementId);return a(d,b)})}
function w(c,a){c=c.F.get(a);if(!c)throw Error(`no element with id ${a}`);return c.X}function v(c,a,b){var d;d||(d={});d.elementId=b;m(c,a,d)}
window.ra=class extends self.sa{constructor(c){super(c,"button");this.F=new Map;this.J=!0;u(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const b=w(this,a);this.J&&b.parentElement.removeChild(b);this.F.delete(a)}],["set-visible",a=>{if(this.J){var b=this.F.get(a.elementId),d=b.X;b.Ea?d.style.display=a.isVisible?"":"none":b.Ha=!!a.isVisible}}],["update-position",a=>{if(this.J){var b=this.F.get(a.elementId),d=b.X,e=this.h;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=a.width+
"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;b.Qa=f;f=e.ta(f);f!==b.v&&(d.remove(),e.R(f).appendChild(d),b.v=f,e.Ba());a=a.htmlZIndex;a!==b.Y&&(b.Y=a,e.Ba());b.Ea||(b.Ea=!0,b.Ha&&(d.style.display=""))}}],["update-state",a=>{const b=w(this,a.elementId);this.va(b,a)}],["focus",a=>{const b=this.xa(w(this,a.elementId));a.focus?b.focus():b.blur()}],["set-css-style",a=>{const b=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?b.style.setProperty(d,
a):b.style[d]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);ca(this,a=>a)}Va(){throw Error("required override");}va(){throw Error("required override");}xa(c){return c}};"use strict";const x=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let z=0;function A(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.ic?new Promise(b=>{const d="c3_resolve_"+z;++z;self[d]=b;a.textContent=c.mc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ea(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let B=new Audio;
const fa={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ha(c){c=await C(c);return(new TextDecoder("utf-8")).decode(c)}
function C(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ia=0;const I=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");I.push(c)};const ja=new Set(["cordova","playable-ad","instant-games"]);let ka=!1;
window.ga=class c{constructor(a){this.m=a.oc;this.aa=null;this.l="";this.M=a.lc;this.da={};this.Ja=this.O=null;this.K=[];this.G=null;this.pb=!0;this.j=[];this.Na=[];this.Oa=!1;this.rb=()=>this.Hb();this.ob=!1;this.Z=null;this.L=-1;this.dc=()=>this.Sb();this.ba=new Set;this.Ra=null;this.sb=[];this.g=a.tb;this.Ga="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;da&&(this.m=!1);if("cordova"===this.g&&this.m&&y){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.m=!1)}this.H()?self.chrome.webview.addEventListener("message",b=>this.gb(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.gb(b));this.ja=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.Wb(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Nb());this.i("runtime","cordova-fetch-local-file",b=>this.Ob(b));this.i("runtime","create-job-worker",()=>this.Pb());this.i("runtime","send-wrapper-extension-message",b=>this.Vb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.eb(a)):this.eb(a)}Wa(){return this.j[0].canvas}ta(a){return Math.min(a,this.j.length-1)}R(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].ea}_GetHTMLWrapElement(a){return this.R(a)}yb(){return x&&
"cordova"===this.g}T(){const a=navigator.userAgent;return x&&ja.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}wb(){return y}Xa(){return y&&ja.has(this.g)}Ya(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}H(){return this.Ya()||"xbox-uwp-webview2"===this.g}async eb(a){this.m&&!await ea()&&(this.m=!1);"macos-wkwebview"===this.g?this.U({type:"ready"}):this.H()&&(this.Zb(),this.sb=(await this.Mb()).registeredComponentIds);
if("playable-ad"===this.g){this.A=self.c3_base64files;this.ja={};await this.Eb();for(let d=0,e=a.P.length;d<e;++d){var b=a.P[d];this.ja.hasOwnProperty(b)?a.P[d]={ic:!0,mc:this.ja[b]}:this.A.hasOwnProperty(b)&&(a.P[d]=URL.createObjectURL(this.A[b]))}a.na=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Za(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.kc?this.l=a.kc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.qc&&(this.da=a.qc);b=new MessageChannel;this.aa=b.port1;this.aa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Rb(d));this.Z=new self.zb(this);await la(this.Z);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Lb(a,b.port2):await this.Kb(a,b.port2)}ya(a){a=this.da.hasOwnProperty(a)?this.da[a]:a.endsWith("/workermain.js")&&this.da.hasOwnProperty("workermain.js")?this.da["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qa(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Ga)return a=await this.pa(d.hc?a:this.M+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}u(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}ua(){return this.H()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?
"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}cb(a){var b=this.l,d=location.href,e=this.u(),f=this.o(),h=this.ua(),g=window.devicePixelRatio,k=c.S(),l=a.vc,n=window.cr_previewImageBlobs||this.A,p=window.cr_previewProjectFileBlobs,q=window.cr_previewProjectFiles,xa=window.cr_swClientId||"";a=a.tb;var ya=(new URLSearchParams(self.location.search)).has("debug"),J=this.Z;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,
windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:q,swClientId:xa,exportType:a,isDebug:ya,ife:!!self.uc,jobScheduler:{inputPort:J.Fa,outputPort:J.Ma,maxNumWorkers:J.bc},supportedAudioFormats:fa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.M+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.M+"opus.wasm.wasm",isFileProtocol:this.Ga,isiOSCordova:this.yb(),isiOSWebView:this.T(),
isWindowsWebView2:this.Ya(),isAnyWebView2Wrapper:this.H(),wrapperComponentIds:this.sb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Lb(a,b){const d=this.ya(a.pc);"preview"===this.g?(this.O=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const p=q=>{this.O.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():n()};this.O.addEventListener("message",p);this.O.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):
this.O=await this.qa(d,this.l,{type:"module",name:"Runtime",hc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,ea:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.na||[],k=a.P;g=await Promise.all(g.map(l=>this.I(l)));k=await Promise.all(k.map(l=>this.I(l)));
if("cordova"===this.g)for(let l=0,n=a.ma.length;l<n;++l){const p=a.ma[l],q=p[0];if(q===a.Sa||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.I(q)}this.O.postMessage(Object.assign(this.cb(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.ma,mainProjectScript:a.Sa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,f,...ma(this.Z)]);this.K=F.map(l=>new l(this));this.bb();K(e);L(h);na(this.G);self.c3_callFunction=
(l,n)=>{var p=this.G;return p.h.Ab(p.W,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.fa("runtime","go-to-last-error-script"))}async Kb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,ea:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.K=F.map(g=>new g(this));this.bb();
K(d);L(e);e=a.P.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.na)){var f=[...a.na].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.I(g)));await Promise.all(e.map(g=>A(g)));e=self.C3_ProjectScriptsStatus;f=a.Sa;const h=a.ma;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.I(k),await A(k),"preview"!==this.g||e[g]||this.hb(g,"main script did not run to completion")}catch(l){this.hb(g,l)}else if("scriptsInEvents.js"===
g||g.endsWith("/scriptsInEvents.js"))k=await this.I(k),await A(k);"preview"===this.g&&"object"!==typeof self.rc.tc?(this.ia(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.cb(a),{isInWorker:!1,messagePort:b,canvas:d,runOnStartupFunctions:I}),na(this.G),this.fb(),this.Ja=self.C3_CreateRuntime(a),
await self.C3_InitRuntime(this.Ja,a))}hb(a,b){this.ia();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}fb(){this.ia()}ia(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Pb(){const a=await oa(this.Z);return{outputPort:a,transferables:[a]}}Wb(a){if(!this.ob){var b=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,ea:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.pb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.pb=!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=
a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,ea:n}=this.j.pop();n.remove();this.m&&!d?this.Na.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),
b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,K(b),L(d),this.j.push({canvas:b,ea:d});for(const l of this.K)if(l instanceof window.ra&&l.J)for(const n of l.F.values())e=l.h.ta(n.Qa),f=n.v,-1!==e&&-1!==f&&e!==f&&(f=n.X,f.remove(),l.h.R(e).appendChild(f),n.v=e);this.Ba();return{addedCanvases:a,transferables:k}}Nb(){for(const a of this.Na)a.remove();this.Na.length=0}Ba(){this.Oa||(this.Oa=!0,this.Za(this.rb))}Hb(){this.Yb(this.rb);
this.Oa=!1;let a=[];for(var b of this.K)if(b instanceof window.ra){var d=b.J?[...b.F.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.v,l=g.v;return k!==l?k-l:h.Y-g.Y});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.v!==b&&(this.ab(b,a.slice(d,e)),b=h.v,d=e)}d<e&&this.ab(b,a.slice(d,e))}ab(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.X);var d=new Set(b);a=this.R(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);for(var g=
f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Jb(){if(this.m)throw Error("not available in worker mode");return this.Ja}fa(a,b,d,e){this.aa.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}Ab(a,b){const d=ia++,e=new Promise((f,h)=>{H.set(d,{resolve:f,reject:h})});this.aa.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;
if("event"===b)return this.Qb(a);if("result"===b)this.Tb(a);else if("runtime-ready"===b)this.Ub();else if("alert-error"===b)this.ia(),alert(a.message);else if("creating-runtime"===b)this.fb();else throw Error(`unknown message '${b}'`);}Qb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ha(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ha(f,!0,
g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ha(f,!1,""+g)}):this.ha(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ha(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.aa.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Tb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=H.get(b);d?e.resolve(a):e.reject(a);H.delete(b)}i(a,b,d){let e=G.get(a);e||(e=new Map,
G.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static oa(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}bb(){for(const a of this.K)if("runtime"===a.W){this.G=a;return}throw Error("cannot find runtime DOM handler");}Rb(a){this.fa("debugger","message",a)}Ub(){for(const a of this.K)a.Ta()}static S(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ka)}static ib(a){ka=!!a}Za(a){this.ba.add(a);
this.Aa()}Yb(a){this.ba.delete(a);0===this.ba.size&&this.$a()}Aa(){-1===this.L&&0<this.ba.size&&(this.L=requestAnimationFrame(this.dc))}$a(){-1!==this.L&&(cancelAnimationFrame(this.L),this.L=-1)}Sb(){this.L=-1;for(const a of this.ba)a();this.Aa()}za(){this.G.za()}Bb(){this.ob=!0}vb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}xb(a){return!this.vb(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Ga&&this.xb(a))?(a.startsWith(this.l)&&
(a=a.substr(this.l.length)),a=await this.pa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ob(a){const b=a.filename;switch(a.as){case "text":return await this.ub(b);case "buffer":return await this.pa(b);default:throw Error("unsupported type");}}Ua(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async ub(a){a=await this.Ua(a);return await ha(a)}wa(){if(D.length&&!(8<=E)){E++;
var a=D.shift();this.Fb(a.filename,a.nc,a.fc)}}pa(a){return new Promise((b,d)=>{D.push({filename:a,nc:e=>{E--;this.wa();b(e)},fc:e=>{E--;this.wa();d(e)}});this.wa()})}async Fb(a,b,d){try{const e=await this.Ua(a),f=await C(e);b(f)}catch(e){d(e)}}gb(a){if("entered-fullscreen"===a)c.ib(!0),M(this.G);else if("exited-fullscreen"===a)c.ib(!1),M(this.G);else if("object"===typeof a){const b=a.type;"directory-handles"!==b&&("wrapper-init-response"===b?(this.Ra(a),this.Ra=null):"extension-message"===b?this.fa("runtime",
"wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}Vb(a){this.U({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}U(a){this.H()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Zb(){window.moveTo=(a,b)=>{this.U({type:"set-window-position",windowX:Math.ceil(a),
windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.U({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Mb(){return this.H()?new Promise(a=>{this.Ra=a;this.U({type:"wrapper-init"})}):Promise.resolve()}async Eb(){const a=[];for(const [b,d]of Object.entries(this.A))a.push(this.Db(b,d));await Promise.all(a)}async Db(a,b){if("object"===typeof b)this.A[a]=new Blob([b.str],{type:b.type}),this.ja[a]=b.str;else{let d=await this.Ib(b);d||(d=this.Gb(b));this.A[a]=d}}async Ib(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}Gb(a){a=this.Xb(a);return this.Cb(a.data,a.jc)}Xb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{jc:a,data:d}}Cb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const N=self.ga,pa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),O={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},P={dispatchUserScriptEvent:!0},Q={dispatchRuntimeEvent:!0};function qa(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}
function ta(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function ua(c){c=URL.createObjectURL(c);try{return await ta(c)}finally{URL.revokeObjectURL(c)}}function va(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const wa=new Set(["input","textarea","datalist","select"]),za=new Set(["canvas","body","html"]);
function R(c){c.target.tagName&&za.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function S(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function Aa(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await ua(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await ua(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let T=!1;document.addEventListener("pause",()=>T=!0);document.addEventListener("resume",()=>T=!1);function K(c){c.addEventListener("selectstart",R);c.addEventListener("gesturehold",R);c.addEventListener("pointerdown",R)}function L(c){c.addEventListener("selectstart",S);c.addEventListener("gesturehold",S);c.addEventListener("touchstart",S)}function na(c){c.mb=!0;c.Ia=c.h.u();c.$=c.h.o()}
function M(c){if(!c.s){var a=N.S();a&&"any"!==c.Pa&&Ba(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.u(),innerHeight:c.o()})}}async function Ca(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Da(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ea(c){return await self.C3_GetSvgImageSize(c.blob)}function Fa(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ga(c){self.setTimeout(()=>{c.lb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>U(c,!0)),document.addEventListener("resume",()=>U(c,!1))):document.addEventListener("visibilitychange",()=>U(c,"hidden"===document.visibilityState));c.ka=!("hidden"!==document.visibilityState&&!T);return{isSuspended:c.ka}}
function Ha(c){c.kb||(c.kb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},O)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},O)}))}
function Ia(c){c.jb||(c.jb=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},O)}}))}async function Ja(c){await qa(c.url)}
function Ka(c,a){c.nb=a.message;-1===c.Da&&(c.Da=setTimeout(()=>{c.Da=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.nb)},250))}function V(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:N.S(),innerWidth:c.u(),innerHeight:c.o()})}
function U(c,a){c.ka!==a&&((c.ka=a)?c.h.$a():c.h.Aa(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.T()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function La(c,a,b){"Backspace"===b.key&&R(b);"nwjs"===c.h.g&&"u"===b.key&&(b.ctrlKey||b.metaKey)&&b.preventDefault();if(!c.s){var d=pa.get(b.code)||b.code;r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},O)}}
function W(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function X(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.La);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},O);"mouse"===b.pointerType&&(c.La=
b.buttons)}}function Y(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.C=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.C=a))}}
function Ma(c,a,b,d){const e=c.u(),f=c.o();c.N=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:N.S(),cssDisplayMode:c.h.ua()}):10>d&&Na(c,e,f,d+1)}function Na(c,a,b,d){-1!==c.N&&clearTimeout(c.N);c.N=setTimeout(()=>Ma(c,a,b,d),48)}
function Ba(c){c=c.Pa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Oa(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
N.oa(class extends self.sa{constructor(c){super(c,"runtime");this.mb=!1;this.N=-1;this.Pa="any";this.ka=this.jb=this.kb=!1;this.la=document.createElement("div");this.la.className="c3-screen-reader-text";this.la.setAttribute("aria-live","polite");document.body.appendChild(this.la);this.D=null;this.s=!1;this.nb="";this.Da=-1;this.lb=!1;this.Ia=c.u();this.$=c.o();this.C=this.ca=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Ca(b));c.i("runtime","raster-svg-image",b=>Da(b));c.i("runtime","get-svg-image-size",b=>Ea(b));c.i("runtime","set-target-orientation",b=>{this.Pa=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Fa(b));c.i("runtime","go-to-script",b=>Fa(b));c.i("runtime","before-start-ticking",()=>Ga(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var d=this.D;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.D&&(this.D.style.display="none")});c.i("runtime","enable-device-orientation",()=>Ha(this));c.i("runtime","enable-device-motion",()=>Ia(this));c.i("runtime","add-stylesheet",b=>Ja(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>{alert(b.message)});c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.la.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+
b.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.h.Wa().style.display="";this.h.Bb()});c.i("runtime","export-to-video-progress",b=>Ka(this,b));c.i("runtime","exported-to-video",b=>{window.ec({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.ec({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||
va(d)||b.preventDefault()});window.addEventListener("selectstart",R);window.addEventListener("gesturehold",R);window.addEventListener("touchstart",R,{passive:!1});window.addEventListener("pointerdown",R,{passive:!1});this.La=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Aa,{passive:!1});window.addEventListener("wheel",Aa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.mb){var b=this.u();var d=this.o();if(this.h.Xa()){if(this.lb){if(this.Ia===
b&&d<this.$){this.ca=this.$-d;Y(this,this.$,this.ca);b=void 0;break a}0<this.ca&&(this.ca=0,Y(this,d,this.ca))}this.Ia=b;this.$=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:N.S(),cssDisplayMode:this.h.ua()});this.h.T()&&(-1!==this.N&&clearTimeout(this.N),Ma(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",
()=>M(this));window.addEventListener("fullscreenerror",b=>V(this,b));window.addEventListener("webkitfullscreenerror",b=>V(this,b));window.addEventListener("mozfullscreenerror",b=>V(this,b));if(c.T()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.Ka=new Set;this.cc=new WeakSet;this.ac=!1}Ta(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Q)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},Q);this.La=0});window.addEventListener("focusin",a=>{a=a.target;(wa.has(a.tagName.toLowerCase())||va(a))&&m(this,"keyboard-blur",null,Q)});window.addEventListener("keydown",a=>La(this,"keydown",a));window.addEventListener("keyup",a=>La(this,"keyup",a));window.addEventListener("mousedown",a=>W(this,"mousedown",a,P));
window.addEventListener("mousemove",a=>W(this,"mousemove",a,P));window.addEventListener("mouseup",a=>W(this,"mouseup",a,P));window.addEventListener("dblclick",a=>W(this,"dblclick",a,O));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.C,pageX:a.pageX,pageY:a.pageY+this.C,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},O)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Oa(a.target)&&
document.activeElement&&!Oa(document.activeElement)&&document.activeElement.blur();X(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{X(this,"pointermove",a)}):window.addEventListener("pointermove",a=>X(this,"pointermove",a));window.addEventListener("pointerup",a=>X(this,"pointerup",a));window.addEventListener("pointercancel",a=>X(this,"pointercancel",a));const c=()=>this.za();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.h.wb()&&!this.h.Xa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.T()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}u(){return this.h.u()}o(){return this.h.o()}za(){var c=
[...this.Ka];this.Ka.clear();if(!this.ac)for(const a of c)(c=a.play())&&c.catch(()=>{this.cc.has(a)||this.Ka.add(a)})}});"use strict";async function la(c){if(c.$b)throw Error("already initialised");c.$b=!0;var a=c.B.ya(("playable-ad"===c.B.g?c.B.M:"")+"dispatchworker.js");c.Ca=await c.B.qa(a,c.V,{name:"DispatchWorker"});a=new MessageChannel;c.Fa=a.port1;c.Ca.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Ma=await oa(c)}function ma(c){return[c.Fa,c.Ma]}
async function oa(c){const a=c.qb.length;var b=c.B.ya(("playable-ad"===c.B.g?c.B.M:"")+"jobworker.js");b=await c.B.qa(b,c.V,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.Ca.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.qb.push(b);return e.port1}
self.zb=class{constructor(c){this.B=c;this.V=c.l;this.V="preview"===c.g?this.V+"workers/":this.V+c.M;this.bc=Math.min(navigator.hardwareConcurrency||2,16);this.Ca=null;this.qb=[];this.Ma=this.Fa=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ga({oc:!0,pc:"workermain.js",P:["scripts/c3runtime.js"],ma:[],Sa:"",lc:"scripts/",na:[],tb:"html5"}));"use strict";
self.ga.oa(class extends self.sa{constructor(c){super(c,"mouse");u(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.h.Wa().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function Z(c){c.stopPropagation()}
self.ga.oa(class extends self.ra{constructor(c){super(c)}Va(c,a){const b=document.createElement("input");var d=b;a.isCheckbox?(b.type="checkbox",d=document.createElement("label"),d.appendChild(b),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):b.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Z);d.addEventListener("pointermove",Z);d.addEventListener("pointerrawupdate",
Z);d.addEventListener("pointerup",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",Z);d.addEventListener("keydown",Z);d.addEventListener("keyup",Z);d.addEventListener("contextmenu",e=>e.preventDefault());b.addEventListener("click",()=>{var e={isChecked:b.checked};e.elementId=c;r(this,"click",e)});a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.va(d,a);return d}xa(c){return"input"===c.tagName.toLowerCase()?c:c.firstChild}va(c,a){const b="input"===c.tagName.toLowerCase()?
c:c.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;c.title=a.title;c===b?b.value=a.text:c.lastChild.textContent=a.text}});
